# Generated by Django 4.2.13 on 2025-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comuna_documento_empresa_fase_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='PRO_ESTADO',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipo_documento',
            name='TD_ESTADO',
            field=models.BooleanField(default=True),
        ),
    ]
