# Generated by Django 4.2.13 on 2025-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_proyecto_pro_estado_tipo_documento_td_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='EMP_ESTADO',
            field=models.BooleanField(default=True),
        ),
    ]
