# Generated by Django 4.2.13 on 2025-10-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fase_proyecto_fa_nnumero_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='TD_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_documento', verbose_name='Id Tipo Documento'),
        ),
        migrations.AddField(
            model_name='fase_proyecto',
            name='FA_COMPLETADO',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FASE_DOCUMENTO',
            fields=[
                ('FTD_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DOC_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.documento', verbose_name='Documento')),
                ('FA_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.fase_proyecto', verbose_name='Id Fase proyecto')),
            ],
            options={
                'db_table': 'FASE_DOCUMENTO',
            },
        ),
    ]
