# Generated by Django 5.2.7 on 2025-11-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_documento_doc_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='TD_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tipo_documento', verbose_name='Id Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='fase_proyecto',
            name='PRO_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto', verbose_name='Id Proyecto'),
        ),
    ]
