# Generated by Django 3.2.6 on 2025-11-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_documento_td_nid_alter_fase_documento_fa_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='DOC_ES_GUIA',
            field=models.BooleanField(default=False),
        ),
    ]
