# Generated by Django 4.2.13 on 2024-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PARAMETRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM_CCODIGOGRUPO', models.CharField(max_length=128)),
                ('PM_CCODIGO', models.CharField(max_length=128)),
                ('PM_CDESCRIPCION', models.CharField(max_length=512)),
                ('PM_CVALOR', models.CharField(max_length=512)),
                ('PM_BPUBLIC', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'PARAMETRO',
            },
        ),
    ]
