# Generated by Django 4.2.13 on 2025-10-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='COMUNA',
            fields=[
                ('COM_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('COM_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('COM_CCODIGO', models.CharField(max_length=64, verbose_name='Código')),
            ],
            options={
                'db_table': 'COMUNA',
            },
        ),
        migrations.CreateModel(
            name='DOCUMENTO',
            fields=[
                ('DOC_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('DOC_NOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('DOC_CONTENIDO', models.ImageField(blank=True, null=True, upload_to='documentos/')),
                ('DOC_FFECHACREACION', models.DateTimeField(auto_now_add=True)),
                ('DOC_APROBADO', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='EMPRESA',
            fields=[
                ('EMP_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('EM_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('EM_RUT', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Rut empresa')),
                ('COM_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.comuna', verbose_name='Id Comuna')),
            ],
            options={
                'db_table': 'EMPRESA',
            },
        ),
        migrations.CreateModel(
            name='FASE_PROYECTO',
            fields=[
                ('FA_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('FA_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('FA_CDESCRICPCION', models.CharField(max_length=1028, verbose_name='Descripcion')),
                ('PRO_FFECHAINCIO', models.DateTimeField()),
                ('PRO_FFECHATERMINO', models.DateTimeField()),
            ],
            options={
                'db_table': 'FASE_PROYECTO',
            },
        ),
        migrations.CreateModel(
            name='FASE_TIPO_DOCUMENTO',
            fields=[
                ('FTD_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('FA_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.fase_proyecto', verbose_name='Id Fase proyecto')),
            ],
            options={
                'db_table': 'FASE_TIPO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='PROYECTO',
            fields=[
                ('PRO_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('PRO_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('PRO_FFECHACREACION', models.DateTimeField(auto_now_add=True)),
                ('EMP_NID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.empresa', verbose_name='Id Empresa')),
            ],
            options={
                'db_table': 'PROYECTO',
            },
        ),
        migrations.CreateModel(
            name='REGION',
            fields=[
                ('RE_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('RE_CNOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
                ('RE_CCODIGO', models.CharField(max_length=64, verbose_name='Código')),
            ],
            options={
                'db_table': 'REGION',
            },
        ),
        migrations.CreateModel(
            name='TIPO_DOCUMENTO',
            fields=[
                ('TD_NID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('TD_NOMBRE', models.CharField(max_length=128, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'TIPO_DOCUMENTO',
            },
        ),
        migrations.DeleteModel(
            name='PARAMETRO',
        ),
        migrations.AddField(
            model_name='fase_tipo_documento',
            name='TD_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.tipo_documento', verbose_name='Id Tipo Documento'),
        ),
        migrations.AddField(
            model_name='fase_proyecto',
            name='PRO_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.proyecto', verbose_name='Id Proyecto'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='RE_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.region', verbose_name='Id Region'),
        ),
    ]
