# Generated by Django 4.2.13 on 2025-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_empresa_emp_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase_proyecto',
            name='FA_NNUMERO_FASE',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Fase'),
        ),
    ]
