# Generated by Django 4.2.13 on 2025-11-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_documento_td_nid_fase_proyecto_fa_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='DOC_CONTENIDO',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
