# Generated by Django 4.2 on 2025-11-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_documento_doc_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='alumnos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Alumno'}, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Alumnos Asignados'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Profesor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Guía'),
        ),
    ]
