# Generated by Django 4.2 on 2025-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_proyecto_alumnos_proyecto_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='DOC_COMENTARIO',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario de Revisión'),
        ),
        migrations.AddField(
            model_name='documento',
            name='DOC_FECHA_MODIFICACION',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='DOC_APROBADO',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
