# Generated by Django 5.2.7 on 2025-11-17 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_documento_td_nid_alter_fase_proyecto_pro_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='TD_NID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.tipo_documento', verbose_name='Id Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='fase_documento',
            name='FA_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fase_proyecto', verbose_name='Id Fase proyecto'),
        ),
        migrations.AlterField(
            model_name='fase_tipo_documento',
            name='FA_NID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fase_proyecto', verbose_name='Id Fase proyecto'),
        ),
    ]
