# Generated by Django 4.2 on 2025-10-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdocumento',
            name='comentario_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemdocumento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdocumento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos_colaboradores/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos_guia/%Y/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_guia', to='formulario.proyecto')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
